# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow checks out code, builds an image, performs a container image
# vulnerability scan with Anchore's Grype tool, and integrates the results with GitHub Advanced Security
# code scanning feature.  For more information on the Anchore scan action usage
# and parameters, see https://github.com/anchore/scan-action. For more
# information on Anchore's container image scanning tool Grype, see
# https://github.com/anchore/grype
name: Grype scan

on:
  workflow_call:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
    - name: Check out the code
      uses: actions/checkout@v3
      
    - name: Running a scan with an json file as an output
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan
      with:
        fail-build: true
        severity-cutoff: critical
        output-format: json
        
    - name: Running a scan with an sarif file as an output
      uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
      id: scan2
      with:
        fail-build: true
        severity-cutoff: critical
        output-format: sarif
        
    - name: Save the json file vulnerability report
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: results.json
        path: ./results.json
        if-no-files-found: warn
        
    - name: Upload vulnerability report to github security scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.scan2.outputs.sarif }}  
      
      
      
    