name: Grype scan

on:
  workflow_call:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
    Scan:
    # Importing a reusable workflow from another repository and branch
        uses: t-kolev/Continuous-SCA-Scanning/.github/workflows/grype.yaml@fine_tuning  
      
      
  Data_Analysis:
    name: Data Analysis
    needs: Grype-Scan
    runs-on: ubuntu-latest
    steps:
      - name: Download result for job Grype-Scan
        uses: actions/download-artifact@v4
        with:
          name: grype_results.json
      
      - name: Check out the code 
        uses: actions/checkout@v3
      
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  
      - name: Running the Python Script
        run: python script.py grype_results.json "Grype.txt"
    