name: Grype scan

on:
  workflow_call:
  push:
    branches: [ "master" ]

jobs:
    Grype-Scan:
      permissions:
        contents: read # for actions/checkout to fetch code
        security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
        actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      runs-on: ubuntu-latest
      steps:
      - name: Check out the code
        uses: actions/checkout@v3
        
      - name: Running a scan with a json file as an output
        uses: anchore/scan-action@v3
        id: scan1
        with:
          fail-build: false
          add-cpes-if-none: true
          output-format:  json
          
      - name: Running a scan with a sarif file as an output
        uses: anchore/scan-action@v3
        id: scan2
        with:
          fail-build: false
          add-cpes-if-none: true
          output-format:  sarif
          
      - name: Save the json vulnerability report to an artifact
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: grype_results
          path: ${{ steps.scan1.outputs.json }}  
      
      - name: Upload vulnerability report to github security scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.scan2.outputs.sarif }}  
      
    Data_Analysis:
      name: Data Analysis
      needs: Grype-Scan
      runs-on: ubuntu-latest
      steps:
        - name: Download result for job Grype-Scan
          uses: actions/download-artifact@v4
          with:
            name: grype_results
            path: t-kolev/ric-plt-xapp-frame/scan/
        
        - name: Check out the code 
          uses: actions/checkout@v3
        
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: '3.10' # install the python version needed

        - name: install python packages
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
    
        - name: Running the Python Script
          run: python script.py t-kolev/ric-plt-xapp-frame/scan/results.json "Grype.txt"
      